version: "3.8"

services:

        mysqldb:
                image: mysql:5.7
                ports:
                        - 3306:3306
                environment:
                        - MYSQL_ROOT_PASSWORD=password

        eureka:
                build: ./micro-api-getway/
                image: eureka-server
                ports:
                        - 8761:8761

        auth:
                build: ./micro-auth-service/
                image: auth-server
                ports:
                        - 9191:9191
                links:
                        - mysqldb:mysql
            	links:
                        - eureka:eureka
            	links:
                        - auth:auth
                volumes:
                        - /opt/docker/log:/app/log
               
        product:
                build: ./micro-product-service/
                image: product-server
                ports:
                        -8380:8380
                links:
                        - mysqldb:mysql
            	links:
                        - eureka:eureka
            	links:
                        - auth:auth
                volumes:
                        - /opt/docker/log:/app/log
	
      	sales:
                build: ./micro-sales-service/
                image: sales-server
                ports:
                        -8380:8380
                links:
                        - mysqldb:mysql
            	links:
                        - eureka:eureka
            	links:
                        - auth:auth
                volumes:
                        - /opt/docker/log:/app/log
                
        zuul:
                build: ./micro-api-getway/
                image: zuul-server
                ports:
                       - 8180:8180

